create table if not exists public.income (id bigint generated by default as identity primary key, user_id uuid not null references auth.users(id) on delete cascade, source text not null, amount numeric(12,2) not null check (amount > 0), date date not null, created_at timestamptz not null default now());
create table if not exists public.expenses (id bigint generated by default as identity primary key, user_id uuid not null references auth.users(id) on delete cascade, item text not null, cost numeric(12,2) not null check (cost > 0), date date not null, created_at timestamptz not null default now());
alter table public.income enable row level security;
alter table public.expenses enable row level security;
create policy "Users manage their income" on public.income for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users manage their expenses" on public.expenses for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create index if not exists income_user_date_idx on public.income(user_id, date desc);
create index if not exists expenses_user_date_idx on public.expenses(user_id, date desc);
